entry-pipeline:
  source:
    otel_trace_source:
  processor:
    - peer_forwarder:
        discovery_mode: "static"
        data_prepper_ips: ["data-prepper1", "data-prepper2"]
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw_processor:
  sink:
    - elasticsearch:
        hosts: [ "https://node-0.example.com:9200" ]
        username: "admin"
        password: "admin"
        trace_analytics_raw: true
service-map-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
        window_duration: 3
  sink:
    - elasticsearch:
        hosts: ["https://node-0.example.com:9200"]
        username: "admin"
        password: "admin"
        trace_analytics_service_map: true