version: "3.7"
services:
  situp:
    restart: unless-stopped
    container_name: situp
    build:
      context: ../../..
      dockerfile: examples/Dockerfile
    working_dir: /app
    command: sh situp-wait-for-elastic-oss.sh
    volumes:
      - ../../situp-wait-for-elastic-oss.sh:/app/situp-wait-for-elastic-oss.sh
      - ../../trace_analytics_elastic_oss.yml:/app/transformation-instance.yml
    ports:
      - "21890:21890"
    networks:
      - my_network
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: elastic
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - my_network
  otel-collector:
    restart: unless-stopped
    image: amazon/aws-otel-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../opentelemetry-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "55680:55680"
    depends_on:
      - situp
    networks:
      - my_network
  mysql:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network
  python-services:
    restart: unless-stopped
    build:
      context: ../python-services
      dockerfile: Dockerfile
    ports:
      - '8082:8082' # inventory
      - '8083:8083' # database
      - '8084:8084' # payment
      - '8085:8085' # auth
      - '8086:8086' # recommendation
    environment:
      - OTLP=otel-collector
      - LOGS=analytics-service
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - WAIT_HOSTS=otel-collector:55680, mysql:3306
    depends_on:
      - otel-collector
      - mysql
      - analytics-service
    networks:
      - my_network
  analytics-service:
    restart: unless-stopped
    build:
      context: ../analytics-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - OTEL_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_RESOURCE_ATTRIBUTES=service.name=analytics-service
    depends_on:
      - otel-collector
    networks:
      - my_network
  client:
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Dockerfile
    environment:
      - OTLP=otel-collector
      - INVENTORY=python-services
      - PAYMENT=python-services
      - AUTH=python-services
      - SLEEP_TIME_IN_SECONDS=5
      - WAIT_HOSTS=python-services:8085 # auth
      - WAIT_AFTER_HOSTS=20
    depends_on:
      - otel-collector
      - python-services
      - analytics-service
    networks:
      - my_network
networks:
  my_network: