raw-pipeline:
  source:
    otel_trace_source:
  processor:
    - otel_trace_raw_processor:
  sink:
    - elasticsearch:
        hosts: [ "https://node-0.example.com:9200" ]
        username: "admin"
        password: "admin"
        trace_analytics_raw: true
