receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  otlp/2:
    endpoint: opendistro-pipes:21890
    ca_file: /etc/demo-situp.crt
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/2]
